// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjaMZuBe5W2lShh9OWE_JY5q8Rs5J2Ps4',
    appId: '1:612989265626:web:5a8a460c86b18cbcc6e7e3',
    messagingSenderId: '612989265626',
    projectId: 'pythonauthapi',
    authDomain: 'pythonauthapi.firebaseapp.com',
    storageBucket: 'pythonauthapi.firebasestorage.app',
    measurementId: 'G-1S91B68C9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWDK9-RzYkmhczZvMSeGQh8TenJbxSA4',
    appId: '1:612989265626:android:0bb395d531ba6eb7c6e7e3',
    messagingSenderId: '612989265626',
    projectId: 'pythonauthapi',
    storageBucket: 'pythonauthapi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoAwD3UiyzoPYgMEnA6joi9I3o2QBjfE',
    appId: '1:612989265626:ios:02f7a5cf1af61109c6e7e3',
    messagingSenderId: '612989265626',
    projectId: 'pythonauthapi',
    storageBucket: 'pythonauthapi.firebasestorage.app',
    iosBundleId: 'com.example.pythonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOoAwD3UiyzoPYgMEnA6joi9I3o2QBjfE',
    appId: '1:612989265626:ios:02f7a5cf1af61109c6e7e3',
    messagingSenderId: '612989265626',
    projectId: 'pythonauthapi',
    storageBucket: 'pythonauthapi.firebasestorage.app',
    iosBundleId: 'com.example.pythonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjaMZuBe5W2lShh9OWE_JY5q8Rs5J2Ps4',
    appId: '1:612989265626:web:0b5caea28b067ca6c6e7e3',
    messagingSenderId: '612989265626',
    projectId: 'pythonauthapi',
    authDomain: 'pythonauthapi.firebaseapp.com',
    storageBucket: 'pythonauthapi.firebasestorage.app',
    measurementId: 'G-08VH7HHE5Z',
  );
}
